using System.Collections.Generic;
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSFAPIUNI.ServiceReference1
{

    //[WebService(Namespace = "http://www.example.org/SincMatMovPS/")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.example.org/SincMatMovPS/", ConfigurationName = "ServiceReference1.SincMatMovPS")]
    public interface SincMatMovPS
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.example.org/SincMatMovPS/SincMatMov", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        WSFAPIUNI.ServiceReference1.SincMatMovResponse SincMatMov(WSFAPIUNI.ServiceReference1.SincMatMovRequest request);

        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.example.org/SincMatMovPS/SincMatMov", ReplyAction = "*")]
        System.Threading.Tasks.Task<WSFAPIUNI.ServiceReference1.SincMatMovResponse> SincMatMovAsync(WSFAPIUNI.ServiceReference1.SincMatMovRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ocu.es/xsd/SincronizarMatMov")]
    public partial class T_TIPO_MATRICULA : object, System.ComponentModel.INotifyPropertyChanged
    {

        private int codigoRegistroField;

        private int codigoPersonaField;

        private string tipoDocumentoField;

        private string numDocumentoField;

        private string nombrePersonaField;

        private string apellidosPersonaField;

        private int codigoProvinciaDomField;

        private bool codigoProvinciaDomFieldSpecified;

        private string nombreProvinciaDomField;

        private int codigoMunicipioDomField;

        private bool codigoMunicipioDomFieldSpecified;

        private string nombreMunicipioDomField;

        private string direccionDomField;

        private string telefonoFijoDomField;

        private string telefonoMovilField;

        private string emailField;

        private string codigoPaisNacimientoField;

        private string periodoAcademicoField;

        private int actividadEconomicaField;

        private int periodoActividadField;

        private string codigoPlanEstudiosField;

        private System.Nullable<int> numeroOrdenExpedienteField;

        private bool numeroOrdenExpedienteFieldSpecified;

        private System.Nullable<int> codigoMovimientoField;

        private bool codigoMovimientoFieldSpecified;

        private string codigoEstudioField;

        private string codigoModalidadPlanField;

        private string codigoSubtipoEstudioField;

        private string codigoFacultadField;
        private string fechaUltimaModificacionField;

        private string tipoPagoField;

        private System.Nullable<int> codigoSistemaFinanciacionField;

        private bool codigoSistemaFinanciacionFieldSpecified;

        private System.Nullable<decimal> importeMatMovField;

        private bool importeMatMovFieldSpecified;

        private System.Nullable<decimal> importeSistemaFinanciacionField;

        private bool importeSistemaFinanciacionFieldSpecified;

        private System.Nullable<decimal> importeRecargosField;

        private bool importeRecargosFieldSpecified;

        private System.Nullable<int> codigoAnulacionField;

        private bool codigoAnulacionFieldSpecified;

        private string fechaAnulacionField;

        private string fechaDesanulacionField;

        private string centroCosteField;

        private string ordenCUCField;

        private string tipoCursoField;

        private string fechaInicioImparticionField;

        private string fechaFinImparticionField;
       

        private List<T_TIPO_DESGLOSE> desglosesMatMovField;

        private List<T_TIPO_RECIBO> recibosMatMovField;
    

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public int codigoRegistro
        {
            get
            {
                return this.codigoRegistroField;
            }
            set
            {
                this.codigoRegistroField = value;
                this.RaisePropertyChanged("codigoRegistro");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public int codigoPersona
        {
            get
            {
                return this.codigoPersonaField;
            }
            set
            {
                this.codigoPersonaField = value;
                this.RaisePropertyChanged("codigoPersona");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string tipoDocumento
        {
            get
            {
                return this.tipoDocumentoField;
            }
            set
            {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string numDocumento
        {
            get
            {
                return this.numDocumentoField;
            }
            set
            {
                this.numDocumentoField = value;
                this.RaisePropertyChanged("numDocumento");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string nombrePersona
        {
            get
            {
                return this.nombrePersonaField;
            }
            set
            {
                this.nombrePersonaField = value;
                this.RaisePropertyChanged("nombrePersona");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string apellidosPersona
        {
            get
            {
                return this.apellidosPersonaField;
            }
            set
            {
                this.apellidosPersonaField = value;
                this.RaisePropertyChanged("apellidosPersona");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public int codigoProvinciaDom
        {
            get
            {
                return this.codigoProvinciaDomField;
            }
            set
            {
                this.codigoProvinciaDomField = value;
                this.RaisePropertyChanged("codigoProvinciaDom");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoProvinciaDomSpecified
        {
            get
            {
                return this.codigoProvinciaDomFieldSpecified;
            }
            set
            {
                this.codigoProvinciaDomFieldSpecified = value;
                this.RaisePropertyChanged("codigoProvinciaDomSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string nombreProvinciaDom
        {
            get
            {
                return this.nombreProvinciaDomField;
            }
            set
            {
                this.nombreProvinciaDomField = value;
                this.RaisePropertyChanged("nombreProvinciaDom");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public int codigoMunicipioDom
        {
            get
            {
                return this.codigoMunicipioDomField;
            }
            set
            {
                this.codigoMunicipioDomField = value;
                this.RaisePropertyChanged("codigoMunicipioDom");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoMunicipioDomSpecified
        {
            get
            {
                return this.codigoMunicipioDomFieldSpecified;
            }
            set
            {
                this.codigoMunicipioDomFieldSpecified = value;
                this.RaisePropertyChanged("codigoMunicipioDomSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string nombreMunicipioDom
        {
            get
            {
                return this.nombreMunicipioDomField;
            }
            set
            {
                this.nombreMunicipioDomField = value;
                this.RaisePropertyChanged("nombreMunicipioDom");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public string direccionDom
        {
            get
            {
                return this.direccionDomField;
            }
            set
            {
                this.direccionDomField = value;
                this.RaisePropertyChanged("direccionDom");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public string telefonoFijoDom
        {
            get
            {
                return this.telefonoFijoDomField;
            }
            set
            {
                this.telefonoFijoDomField = value;
                this.RaisePropertyChanged("telefonoFijoDom");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public string telefonoMovil
        {
            get
            {
                return this.telefonoMovilField;
            }
            set
            {
                this.telefonoMovilField = value;
                this.RaisePropertyChanged("telefonoMovil");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        public string codigoPaisNacimiento
        {
            get
            {
                return this.codigoPaisNacimientoField;
            }
            set
            {
                this.codigoPaisNacimientoField = value;
                this.RaisePropertyChanged("codigoPaisNacimiento");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
        public string periodoAcademico
        {
            get
            {
                return this.periodoAcademicoField;
            }
            set
            {
                this.periodoAcademicoField = value;
                this.RaisePropertyChanged("periodoAcademico");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 16)]
        public int actividadEconomica
        {
            get
            {
                return this.actividadEconomicaField;
            }
            set
            {
                this.actividadEconomicaField = value;
                this.RaisePropertyChanged("actividadEconomica");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 17)]
        public int periodoActividad
        {
            get
            {
                return this.periodoActividadField;
            }
            set
            {
                this.periodoActividadField = value;
                this.RaisePropertyChanged("periodoActividad");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 18)]
        public string codigoPlanEstudios
        {
            get
            {
                return this.codigoPlanEstudiosField;
            }
            set
            {
                this.codigoPlanEstudiosField = value;
                this.RaisePropertyChanged("codigoPlanEstudios");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 19)]
        public System.Nullable<int> numeroOrdenExpediente
        {
            get
            {
                return this.numeroOrdenExpedienteField;
            }
            set
            {
                this.numeroOrdenExpedienteField = value;
                this.RaisePropertyChanged("numeroOrdenExpediente");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroOrdenExpedienteSpecified
        {
            get
            {
                return this.numeroOrdenExpedienteFieldSpecified;
            }
            set
            {
                this.numeroOrdenExpedienteFieldSpecified = value;
                this.RaisePropertyChanged("numeroOrdenExpedienteSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 20)]
        public System.Nullable<int> codigoMovimiento
        {
            get
            {
                return this.codigoMovimientoField;
            }
            set
            {
                this.codigoMovimientoField = value;
                this.RaisePropertyChanged("codigoMovimiento");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoMovimientoSpecified
        {
            get
            {
                return this.codigoMovimientoFieldSpecified;
            }
            set
            {
                this.codigoMovimientoFieldSpecified = value;
                this.RaisePropertyChanged("codigoMovimientoSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 21)]
        public string codigoEstudio
        {
            get
            {
                return this.codigoEstudioField;
            }
            set
            {
                this.codigoEstudioField = value;
                this.RaisePropertyChanged("codigoEstudio");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 22)]
        public string codigoModalidadPlan
        {
            get
            {
                return this.codigoModalidadPlanField;
            }
            set
            {
                this.codigoModalidadPlanField = value;
                this.RaisePropertyChanged("codigoModalidadPlan");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 23)]
        public string codigoSubtipoEstudio
        {
            get
            {
                return this.codigoSubtipoEstudioField;
            }
            set
            {
                this.codigoSubtipoEstudioField = value;
                this.RaisePropertyChanged("codigoSubtipoEstudio");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 24)]
        public string codigoFacultad
        {
            get
            {
                return this.codigoFacultadField;
            }
            set
            {
                this.codigoFacultadField = value;
                this.RaisePropertyChanged("codigoFacultad");
            }
        }



        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 25)]
        public string fechaUltimaModificacion
        {
            get
            {
                return this.fechaUltimaModificacionField;
            }
            set
            {
                this.fechaUltimaModificacionField = value;
                this.RaisePropertyChanged("fechaUltimaModificacion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 26)]
        public string tipoPago
        {
            get
            {
                return this.tipoPagoField;
            }
            set
            {
                this.tipoPagoField = value;
                this.RaisePropertyChanged("tipoPago");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 27)]
        public System.Nullable<int> codigoSistemaFinanciacion
        {
            get
            {
                return this.codigoSistemaFinanciacionField;
            }
            set
            {
                this.codigoSistemaFinanciacionField = value;
                this.RaisePropertyChanged("codigoSistemaFinanciacion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSistemaFinanciacionSpecified
        {
            get
            {
                return this.codigoSistemaFinanciacionFieldSpecified;
            }
            set
            {
                this.codigoSistemaFinanciacionFieldSpecified = value;
                this.RaisePropertyChanged("codigoSistemaFinanciacionSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 28)]
        public System.Nullable<decimal> importeMatMov
        {
            get
            {
                return this.importeMatMovField;
            }
            set
            {
                this.importeMatMovField = value;
                this.RaisePropertyChanged("importeMatMov");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool importeMatMovSpecified
        {
            get
            {
                return this.importeMatMovFieldSpecified;
            }
            set
            {
                this.importeMatMovFieldSpecified = value;
                this.RaisePropertyChanged("importeMatMovSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 29)]
        public System.Nullable<decimal> importeSistemaFinanciacion
        {
            get
            {
                return this.importeSistemaFinanciacionField;
            }
            set
            {
                this.importeSistemaFinanciacionField = value;
                this.RaisePropertyChanged("importeSistemaFinanciacion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool importeSistemaFinanciacionSpecified
        {
            get
            {
                return this.importeSistemaFinanciacionFieldSpecified;
            }
            set
            {
                this.importeSistemaFinanciacionFieldSpecified = value;
                this.RaisePropertyChanged("importeSistemaFinanciacionSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 30)]
        public System.Nullable<decimal> importeRecargos
        {
            get
            {
                return this.importeRecargosField;
            }
            set
            {
                this.importeRecargosField = value;
                this.RaisePropertyChanged("importeRecargos");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool importeRecargosSpecified
        {
            get
            {
                return this.importeRecargosFieldSpecified;
            }
            set
            {
                this.importeRecargosFieldSpecified = value;
                this.RaisePropertyChanged("importeRecargosSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 31)]
        public System.Nullable<int> codigoAnulacion
        {
            get
            {
                return this.codigoAnulacionField;
            }
            set
            {
                this.codigoAnulacionField = value;
                this.RaisePropertyChanged("codigoAnulacion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoAnulacionSpecified
        {
            get
            {
                return this.codigoAnulacionFieldSpecified;
            }
            set
            {
                this.codigoAnulacionFieldSpecified = value;
                this.RaisePropertyChanged("codigoAnulacionSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 32)]
        public string fechaAnulacion
        {
            get
            {
                return this.fechaAnulacionField;
            }
            set
            {
                this.fechaAnulacionField = value;
                this.RaisePropertyChanged("fechaAnulacion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 33)]
        public string fechaDesanulacion
        {
            get
            {
                return this.fechaDesanulacionField;
            }
            set
            {
                this.fechaDesanulacionField = value;
                this.RaisePropertyChanged("fechaDesanulacion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 34)]
        public string centroCoste
        {
            get
            {
                return this.centroCosteField;
            }
            set
            {
                this.centroCosteField = value;
                this.RaisePropertyChanged("centroCoste");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 35)]
        public string ordenCUC
        {
            get
            {
                return this.ordenCUCField;
            }
            set
            {
                this.ordenCUCField = value;
                this.RaisePropertyChanged("ordenCUC");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 36)]
        public string tipoCurso
        {
            get
            {
                return this.tipoCursoField;
            }
            set
            {
                this.tipoCursoField = value;
                this.RaisePropertyChanged("tipoCurso");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 37)]
        public string fechaInicioImparticion
        {
            get
            {
                return this.fechaInicioImparticionField;
            }
            set
            {
                this.fechaInicioImparticionField = value;
                this.RaisePropertyChanged("fechaInicioImparticion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 38)]
        public string fechaFinImparticion
        {
            get
            {
                return this.fechaFinImparticionField;
            }
            set
            {
                this.fechaFinImparticionField = value;
                this.RaisePropertyChanged("fechaFinImparticion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 39)]
        [System.Xml.Serialization.XmlArrayItemAttribute("tiposDesglose", typeof(T_TIPO_DESGLOSE), IsNullable = false)]
        public List<T_TIPO_DESGLOSE> desglosesMatMov
        {
            get
            {
                return this.desglosesMatMovField;
            }
            set
            {
                this.desglosesMatMovField = value;
                this.RaisePropertyChanged("desglosesMatMov");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 40)]
        [System.Xml.Serialization.XmlArrayItemAttribute("tiposRecibo", typeof(T_TIPO_RECIBO), IsNullable = false)]
        public List<T_TIPO_RECIBO> recibosMatMov
        {
            get
            {
                return this.recibosMatMovField;
            }
            set
            {
                this.recibosMatMovField = value;
                this.RaisePropertyChanged("recibosMatMov");
            }
        }

 
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ocu.es/xsd/SincronizarMatMov")]
    public partial class T_TIPO_DESGLOSE : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string tipoConceptoField;

        private int codigoConceptoField;

        private string nombreConceptoField;

        private decimal importeConceptoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string tipoConcepto
        {
            get
            {
                return this.tipoConceptoField;
            }
            set
            {
                this.tipoConceptoField = value;
                this.RaisePropertyChanged("tipoConcepto");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public int codigoConcepto
        {
            get
            {
                return this.codigoConceptoField;
            }
            set
            {
                this.codigoConceptoField = value;
                this.RaisePropertyChanged("codigoConcepto");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string nombreConcepto
        {
            get
            {
                return this.nombreConceptoField;
            }
            set
            {
                this.nombreConceptoField = value;
                this.RaisePropertyChanged("nombreConcepto");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public decimal importeConcepto
        {
            get
            {
                return this.importeConceptoField;
            }
            set
            {
                this.importeConceptoField = value;
                this.RaisePropertyChanged("importeConcepto");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ocu.es/xsd/SincronizarMatMov")]
    public partial class T_TIPO_RECIBO_COMPENSACION : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string referenciaReciboCompensadoField;

        private decimal importeReciboCompensadoField;

        private string fechaCobroReciboCompensadoField;

        private string tipoCompensacionField;

        private System.Nullable<decimal> importeCobradoCompensadoField;

        private bool importeCobradoCompensadoFieldSpecified;

        private string modoCobroCompensadoField;

        private string codigoBancoIngresoCompensadoField;

        private string entidadPagadoraCompensadoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string referenciaReciboCompensado
        {
            get
            {
                return this.referenciaReciboCompensadoField;
            }
            set
            {
                this.referenciaReciboCompensadoField = value;
                this.RaisePropertyChanged("referenciaReciboCompensado");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public decimal importeReciboCompensado
        {
            get
            {
                return this.importeReciboCompensadoField;
            }
            set
            {
                this.importeReciboCompensadoField = value;
                this.RaisePropertyChanged("importeReciboCompensado");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string fechaCobroReciboCompensado
        {
            get
            {
                return this.fechaCobroReciboCompensadoField;
            }
            set
            {
                this.fechaCobroReciboCompensadoField = value;
                this.RaisePropertyChanged("fechaCobroReciboCompensado");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string tipoCompensacion
        {
            get
            {
                return this.tipoCompensacionField;
            }
            set
            {
                this.tipoCompensacionField = value;
                this.RaisePropertyChanged("tipoCompensacion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 4)]
        public System.Nullable<decimal> importeCobradoCompensado
        {
            get
            {
                return this.importeCobradoCompensadoField;
            }
            set
            {
                this.importeCobradoCompensadoField = value;
                this.RaisePropertyChanged("importeCobradoCompensado");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool importeCobradoCompensadoSpecified
        {
            get
            {
                return this.importeCobradoCompensadoFieldSpecified;
            }
            set
            {
                this.importeCobradoCompensadoFieldSpecified = value;
                this.RaisePropertyChanged("importeCobradoCompensadoSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string modoCobroCompensado
        {
            get
            {
                return this.modoCobroCompensadoField;
            }
            set
            {
                this.modoCobroCompensadoField = value;
                this.RaisePropertyChanged("modoCobroCompensado");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string codigoBancoIngresoCompensado
        {
            get
            {
                return this.codigoBancoIngresoCompensadoField;
            }
            set
            {
                this.codigoBancoIngresoCompensadoField = value;
                this.RaisePropertyChanged("codigoBancoIngresoCompensado");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string entidadPagadoraCompensado
        {
            get
            {
                return this.entidadPagadoraCompensadoField;
            }
            set
            {
                this.entidadPagadoraCompensadoField = value;
                this.RaisePropertyChanged("entidadPagadoraCompensado");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ocu.es/xsd/SincronizarMatMov")]
    public partial class T_TIPO_RECIBO : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string referenciaReciboField;

        private string fechaEmisionField;

        private decimal importePagoOportunoField;

        private string fechaPagoOportunoHastaField;

        private System.Nullable<decimal> importePago1Field;

        private bool importePago1FieldSpecified;

        private string fechaPago1HastaField;

        private System.Nullable<decimal> importePago2Field;

        private bool importePago2FieldSpecified;

        private string fechaPago2HastaField;

        private System.Nullable<decimal> importePago3Field;

        private bool importePago3FieldSpecified;

        private string fechaPago3HastaField;

        private System.Nullable<int> codigoSistemaFinanciacionField;

        private bool codigoSistemaFinanciacionFieldSpecified;

        private System.Nullable<decimal> importeSistemaFinanciacionField;

        private bool importeSistemaFinanciacionFieldSpecified;

        private int plazoPagoField;

        private int codigoFormaPagoField;

        private string esCobradoField;

        private string fechaCobroField;

        private System.Nullable<decimal> importeCobradoField;

        private bool importeCobradoFieldSpecified;

        private string modoCobroField;

        private string estadoSolicitudDevolucionField;

        private string codigoBancoIngresoField;

        private string entidadPagadoraField;

        private string esPagoOnLineField;

        private string idOperacionBancariaOnLineField;

        private List<T_TIPO_RECIBO_COMPENSACION> recibosCompensacionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string referenciaRecibo
        {
            get
            {
                return this.referenciaReciboField;
            }
            set
            {
                this.referenciaReciboField = value;
                this.RaisePropertyChanged("referenciaRecibo");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string fechaEmision
        {
            get
            {
                return this.fechaEmisionField;
            }
            set
            {
                this.fechaEmisionField = value;
                this.RaisePropertyChanged("fechaEmision");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public decimal ImportePagoOportuno
        {
            get
            {
                return this.importePagoOportunoField;
            }
            set
            {
                this.importePagoOportunoField = value;
                this.RaisePropertyChanged("ImportePagoOportuno");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string fechaPagoOportunoHasta
        {
            get
            {
                return this.fechaPagoOportunoHastaField;
            }
            set
            {
                this.fechaPagoOportunoHastaField = value;
                this.RaisePropertyChanged("fechaPagoOportunoHasta");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 4)]
        public System.Nullable<decimal> importePago1
        {
            get
            {
                return this.importePago1Field;
            }
            set
            {
                this.importePago1Field = value;
                this.RaisePropertyChanged("importePago1");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool importePago1Specified
        {
            get
            {
                return this.importePago1FieldSpecified;
            }
            set
            {
                this.importePago1FieldSpecified = value;
                this.RaisePropertyChanged("importePago1Specified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string fechaPago1Hasta
        {
            get
            {
                return this.fechaPago1HastaField;
            }
            set
            {
                this.fechaPago1HastaField = value;
                this.RaisePropertyChanged("fechaPago1Hasta");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 6)]
        public System.Nullable<decimal> importePago2
        {
            get
            {
                return this.importePago2Field;
            }
            set
            {
                this.importePago2Field = value;
                this.RaisePropertyChanged("importePago2");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool importePago2Specified
        {
            get
            {
                return this.importePago2FieldSpecified;
            }
            set
            {
                this.importePago2FieldSpecified = value;
                this.RaisePropertyChanged("importePago2Specified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string fechaPago2Hasta
        {
            get
            {
                return this.fechaPago2HastaField;
            }
            set
            {
                this.fechaPago2HastaField = value;
                this.RaisePropertyChanged("fechaPago2Hasta");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 8)]
        public System.Nullable<decimal> importePago3
        {
            get
            {
                return this.importePago3Field;
            }
            set
            {
                this.importePago3Field = value;
                this.RaisePropertyChanged("importePago3");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool importePago3Specified
        {
            get
            {
                return this.importePago3FieldSpecified;
            }
            set
            {
                this.importePago3FieldSpecified = value;
                this.RaisePropertyChanged("importePago3Specified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string fechaPago3Hasta
        {
            get
            {
                return this.fechaPago3HastaField;
            }
            set
            {
                this.fechaPago3HastaField = value;
                this.RaisePropertyChanged("fechaPago3Hasta");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 10)]
        public System.Nullable<int> codigoSistemaFinanciacion
        {
            get
            {
                return this.codigoSistemaFinanciacionField;
            }
            set
            {
                this.codigoSistemaFinanciacionField = value;
                this.RaisePropertyChanged("codigoSistemaFinanciacion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSistemaFinanciacionSpecified
        {
            get
            {
                return this.codigoSistemaFinanciacionFieldSpecified;
            }
            set
            {
                this.codigoSistemaFinanciacionFieldSpecified = value;
                this.RaisePropertyChanged("codigoSistemaFinanciacionSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 11)]
        public System.Nullable<decimal> importeSistemaFinanciacion
        {
            get
            {
                return this.importeSistemaFinanciacionField;
            }
            set
            {
                this.importeSistemaFinanciacionField = value;
                this.RaisePropertyChanged("importeSistemaFinanciacion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool importeSistemaFinanciacionSpecified
        {
            get
            {
                return this.importeSistemaFinanciacionFieldSpecified;
            }
            set
            {
                this.importeSistemaFinanciacionFieldSpecified = value;
                this.RaisePropertyChanged("importeSistemaFinanciacionSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public int plazoPago
        {
            get
            {
                return this.plazoPagoField;
            }
            set
            {
                this.plazoPagoField = value;
                this.RaisePropertyChanged("plazoPago");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public int codigoFormaPago
        {
            get
            {
                return this.codigoFormaPagoField;
            }
            set
            {
                this.codigoFormaPagoField = value;
                this.RaisePropertyChanged("codigoFormaPago");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        public string esCobrado
        {
            get
            {
                return this.esCobradoField;
            }
            set
            {
                this.esCobradoField = value;
                this.RaisePropertyChanged("esCobrado");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
        public string fechaCobro
        {
            get
            {
                return this.fechaCobroField;
            }
            set
            {
                this.fechaCobroField = value;
                this.RaisePropertyChanged("fechaCobro");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 16)]
        public System.Nullable<decimal> importeCobrado
        {
            get
            {
                return this.importeCobradoField;
            }
            set
            {
                this.importeCobradoField = value;
                this.RaisePropertyChanged("importeCobrado");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool importeCobradoSpecified
        {
            get
            {
                return this.importeCobradoFieldSpecified;
            }
            set
            {
                this.importeCobradoFieldSpecified = value;
                this.RaisePropertyChanged("importeCobradoSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 17)]
        public string modoCobro
        {
            get
            {
                return this.modoCobroField;
            }
            set
            {
                this.modoCobroField = value;
                this.RaisePropertyChanged("modoCobro");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 18)]
        public string estadoSolicitudDevolucion
        {
            get
            {
                return this.estadoSolicitudDevolucionField;
            }
            set
            {
                this.estadoSolicitudDevolucionField = value;
                this.RaisePropertyChanged("estadoSolicitudDevolucion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 19)]
        public string codigoBancoIngreso
        {
            get
            {
                return this.codigoBancoIngresoField;
            }
            set
            {
                this.codigoBancoIngresoField = value;
                this.RaisePropertyChanged("codigoBancoIngreso");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 20)]
        public string entidadPagadora
        {
            get
            {
                return this.entidadPagadoraField;
            }
            set
            {
                this.entidadPagadoraField = value;
                this.RaisePropertyChanged("entidadPagadora");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 21)]
        public string esPagoOnLine
        {
            get
            {
                return this.esPagoOnLineField;
            }
            set
            {
                this.esPagoOnLineField = value;
                this.RaisePropertyChanged("esPagoOnLine");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 22)]
        public string IdOperacionBancariaOnLine
        {
            get
            {
                return this.idOperacionBancariaOnLineField;
            }
            set
            {
                this.idOperacionBancariaOnLineField = value;
                this.RaisePropertyChanged("IdOperacionBancariaOnLine");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 23)]
        [System.Xml.Serialization.XmlArrayItemAttribute("tiposReciboCompensacion", typeof(T_TIPO_RECIBO_COMPENSACION), IsNullable = false)]
        public List<T_TIPO_RECIBO_COMPENSACION> recibosCompensacion
        {
            get
            {
                return this.recibosCompensacionField;
            }
            set
            {
                this.recibosCompensacionField = value;
                this.RaisePropertyChanged("recibosCompensacion");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "sincronizarMatMovRequest", WrapperNamespace = "http://www.ocu.es/xsd/SincronizarMatMov", IsWrapped = true)]
    public partial class SincMatMovRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.ocu.es/xsd/SincronizarMatMov", Order = 0)]
        public WSFAPIUNI.ServiceReference1.T_TIPO_MATRICULA tipoMatricula;

        public SincMatMovRequest()
        {
        }

        public SincMatMovRequest(WSFAPIUNI.ServiceReference1.T_TIPO_MATRICULA tipoMatricula)
        {
            this.tipoMatricula = tipoMatricula;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "sincronizarMatMovResponse", WrapperNamespace = "http://www.ocu.es/xsd/SincronizarMatMov", IsWrapped = true)]
    public partial class SincMatMovResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.ocu.es/xsd/SincronizarMatMov", Order = 0)]
        public int codigoRegistro;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.ocu.es/xsd/SincronizarMatMov", Order = 1)]
        public int codigoRespuesta;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.ocu.es/xsd/SincronizarMatMov", Order = 2)]
        public string mensajeRespuesta;

        public SincMatMovResponse()
        {
        }

        public SincMatMovResponse(int codigoRegistro, int codigoRespuesta, string mensajeRespuesta)
        {
            this.codigoRegistro = codigoRegistro;
            this.codigoRespuesta = codigoRespuesta;
            this.mensajeRespuesta = mensajeRespuesta;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SincMatMovPSChannel : WSFAPIUNI.ServiceReference1.SincMatMovPS, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SincMatMovPSClient : System.ServiceModel.ClientBase<WSFAPIUNI.ServiceReference1.SincMatMovPS>, WSFAPIUNI.ServiceReference1.SincMatMovPS
    {

        public SincMatMovPSClient()
        {
        }

        public SincMatMovPSClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public SincMatMovPSClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public SincMatMovPSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public SincMatMovPSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFAPIUNI.ServiceReference1.SincMatMovResponse WSFAPIUNI.ServiceReference1.SincMatMovPS.SincMatMov(WSFAPIUNI.ServiceReference1.SincMatMovRequest request)
        {
            return base.Channel.SincMatMov(request);
        }

        public int SincMatMov(WSFAPIUNI.ServiceReference1.T_TIPO_MATRICULA tipoMatricula, out int codigoRespuesta, out string mensajeRespuesta)
        {
            WSFAPIUNI.ServiceReference1.SincMatMovRequest inValue = new WSFAPIUNI.ServiceReference1.SincMatMovRequest();
            inValue.tipoMatricula = tipoMatricula;
            WSFAPIUNI.ServiceReference1.SincMatMovResponse retVal = ((WSFAPIUNI.ServiceReference1.SincMatMovPS)(this)).SincMatMov(inValue);
            codigoRespuesta = retVal.codigoRespuesta;
            mensajeRespuesta = retVal.mensajeRespuesta;
            return retVal.codigoRegistro;
        }

        public System.Threading.Tasks.Task<WSFAPIUNI.ServiceReference1.SincMatMovResponse> SincMatMovAsync(WSFAPIUNI.ServiceReference1.SincMatMovRequest request)
        {
            return base.Channel.SincMatMovAsync(request);
        }
    }
}
