//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WSFAPIUNI.WsFaFactu {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SFAFACTUSoap", Namespace="http://seven/")]
    public partial class SFAFACTU : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InsertarFaFactuOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertarFaDfactOperationCompleted;
        
        private System.Threading.SendOrPostCallback AplicarFacturaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AnularFacturaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AnularHOperationCompleted;
        
        private System.Threading.SendOrPostCallback AnularFacturaConCruceOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarFacturaOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertarFacturaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerarReporteFaFactuOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SFAFACTU() {
            this.Url = global::WSFAPIUNI.Properties.Settings.Default.WSFAPIUNI_WsFaFactu_SFAFACTU;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InsertarFaFactuCompletedEventHandler InsertarFaFactuCompleted;
        
        /// <remarks/>
        public event InsertarFaDfactCompletedEventHandler InsertarFaDfactCompleted;
        
        /// <remarks/>
        public event AplicarFacturaCompletedEventHandler AplicarFacturaCompleted;
        
        /// <remarks/>
        public event AnularFacturaCompletedEventHandler AnularFacturaCompleted;
        
        /// <remarks/>
        public event AnularHCompletedEventHandler AnularHCompleted;
        
        /// <remarks/>
        public event AnularFacturaConCruceCompletedEventHandler AnularFacturaConCruceCompleted;
        
        /// <remarks/>
        public event EliminarFacturaCompletedEventHandler EliminarFacturaCompleted;
        
        /// <remarks/>
        public event InsertarFacturaCompletedEventHandler InsertarFacturaCompleted;
        
        /// <remarks/>
        public event GenerarReporteFaFactuCompletedEventHandler GenerarReporteFaFactuCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seven/InsertarFaFactu", RequestNamespace="http://seven/", ResponseNamespace="http://seven/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertarFaFactu(int emp_codi, int top_codi, int fac_nume, System.DateTime fac_fech, string arb_csuc, string fac_desc, string cli_coda, int dcl_codd, int mon_codi, System.DateTime fac_feta, string fac_tipo, System.DateTime fac_feci, System.DateTime fac_fecf, string fac_cref) {
            object[] results = this.Invoke("InsertarFaFactu", new object[] {
                        emp_codi,
                        top_codi,
                        fac_nume,
                        fac_fech,
                        arb_csuc,
                        fac_desc,
                        cli_coda,
                        dcl_codd,
                        mon_codi,
                        fac_feta,
                        fac_tipo,
                        fac_feci,
                        fac_fecf,
                        fac_cref});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertarFaFactuAsync(int emp_codi, int top_codi, int fac_nume, System.DateTime fac_fech, string arb_csuc, string fac_desc, string cli_coda, int dcl_codd, int mon_codi, System.DateTime fac_feta, string fac_tipo, System.DateTime fac_feci, System.DateTime fac_fecf, string fac_cref) {
            this.InsertarFaFactuAsync(emp_codi, top_codi, fac_nume, fac_fech, arb_csuc, fac_desc, cli_coda, dcl_codd, mon_codi, fac_feta, fac_tipo, fac_feci, fac_fecf, fac_cref, null);
        }
        
        /// <remarks/>
        public void InsertarFaFactuAsync(int emp_codi, int top_codi, int fac_nume, System.DateTime fac_fech, string arb_csuc, string fac_desc, string cli_coda, int dcl_codd, int mon_codi, System.DateTime fac_feta, string fac_tipo, System.DateTime fac_feci, System.DateTime fac_fecf, string fac_cref, object userState) {
            if ((this.InsertarFaFactuOperationCompleted == null)) {
                this.InsertarFaFactuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarFaFactuOperationCompleted);
            }
            this.InvokeAsync("InsertarFaFactu", new object[] {
                        emp_codi,
                        top_codi,
                        fac_nume,
                        fac_fech,
                        arb_csuc,
                        fac_desc,
                        cli_coda,
                        dcl_codd,
                        mon_codi,
                        fac_feta,
                        fac_tipo,
                        fac_feci,
                        fac_fecf,
                        fac_cref}, this.InsertarFaFactuOperationCompleted, userState);
        }
        
        private void OnInsertarFaFactuOperationCompleted(object arg) {
            if ((this.InsertarFaFactuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarFaFactuCompleted(this, new InsertarFaFactuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seven/InsertarFaDfact", RequestNamespace="http://seven/", ResponseNamespace="http://seven/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertarFaDfact(
                    int emp_codi, 
                    int fac_cont, 
                    int dfa_cont, 
                    int bod_codi, 
                    string pro_codi, 
                    int uni_codi, 
                    double dfa_cant, 
                    double dfa_valo, 
                    string dfa_tide, 
                    double dfa_pvde, 
                    string dfa_desc, 
                    string dfa_dest, 
                    string arb_csuc, 
                    string arb_care, 
                    string arb_cpro, 
                    string arb_ccec) {
            object[] results = this.Invoke("InsertarFaDfact", new object[] {
                        emp_codi,
                        fac_cont,
                        dfa_cont,
                        bod_codi,
                        pro_codi,
                        uni_codi,
                        dfa_cant,
                        dfa_valo,
                        dfa_tide,
                        dfa_pvde,
                        dfa_desc,
                        dfa_dest,
                        arb_csuc,
                        arb_care,
                        arb_cpro,
                        arb_ccec});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertarFaDfactAsync(
                    int emp_codi, 
                    int fac_cont, 
                    int dfa_cont, 
                    int bod_codi, 
                    string pro_codi, 
                    int uni_codi, 
                    double dfa_cant, 
                    double dfa_valo, 
                    string dfa_tide, 
                    double dfa_pvde, 
                    string dfa_desc, 
                    string dfa_dest, 
                    string arb_csuc, 
                    string arb_care, 
                    string arb_cpro, 
                    string arb_ccec) {
            this.InsertarFaDfactAsync(emp_codi, fac_cont, dfa_cont, bod_codi, pro_codi, uni_codi, dfa_cant, dfa_valo, dfa_tide, dfa_pvde, dfa_desc, dfa_dest, arb_csuc, arb_care, arb_cpro, arb_ccec, null);
        }
        
        /// <remarks/>
        public void InsertarFaDfactAsync(
                    int emp_codi, 
                    int fac_cont, 
                    int dfa_cont, 
                    int bod_codi, 
                    string pro_codi, 
                    int uni_codi, 
                    double dfa_cant, 
                    double dfa_valo, 
                    string dfa_tide, 
                    double dfa_pvde, 
                    string dfa_desc, 
                    string dfa_dest, 
                    string arb_csuc, 
                    string arb_care, 
                    string arb_cpro, 
                    string arb_ccec, 
                    object userState) {
            if ((this.InsertarFaDfactOperationCompleted == null)) {
                this.InsertarFaDfactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarFaDfactOperationCompleted);
            }
            this.InvokeAsync("InsertarFaDfact", new object[] {
                        emp_codi,
                        fac_cont,
                        dfa_cont,
                        bod_codi,
                        pro_codi,
                        uni_codi,
                        dfa_cant,
                        dfa_valo,
                        dfa_tide,
                        dfa_pvde,
                        dfa_desc,
                        dfa_dest,
                        arb_csuc,
                        arb_care,
                        arb_cpro,
                        arb_ccec}, this.InsertarFaDfactOperationCompleted, userState);
        }
        
        private void OnInsertarFaDfactOperationCompleted(object arg) {
            if ((this.InsertarFaDfactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarFaDfactCompleted(this, new InsertarFaDfactCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seven/AplicarFactura", RequestNamespace="http://seven/", ResponseNamespace="http://seven/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AplicarFactura(int emp_codi, int fac_cont) {
            object[] results = this.Invoke("AplicarFactura", new object[] {
                        emp_codi,
                        fac_cont});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AplicarFacturaAsync(int emp_codi, int fac_cont) {
            this.AplicarFacturaAsync(emp_codi, fac_cont, null);
        }
        
        /// <remarks/>
        public void AplicarFacturaAsync(int emp_codi, int fac_cont, object userState) {
            if ((this.AplicarFacturaOperationCompleted == null)) {
                this.AplicarFacturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAplicarFacturaOperationCompleted);
            }
            this.InvokeAsync("AplicarFactura", new object[] {
                        emp_codi,
                        fac_cont}, this.AplicarFacturaOperationCompleted, userState);
        }
        
        private void OnAplicarFacturaOperationCompleted(object arg) {
            if ((this.AplicarFacturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AplicarFacturaCompleted(this, new AplicarFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seven/AnularFactura", RequestNamespace="http://seven/", ResponseNamespace="http://seven/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AnularFactura(int emp_codi, int fac_cont) {
            object[] results = this.Invoke("AnularFactura", new object[] {
                        emp_codi,
                        fac_cont});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AnularFacturaAsync(int emp_codi, int fac_cont) {
            this.AnularFacturaAsync(emp_codi, fac_cont, null);
        }
        
        /// <remarks/>
        public void AnularFacturaAsync(int emp_codi, int fac_cont, object userState) {
            if ((this.AnularFacturaOperationCompleted == null)) {
                this.AnularFacturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAnularFacturaOperationCompleted);
            }
            this.InvokeAsync("AnularFactura", new object[] {
                        emp_codi,
                        fac_cont}, this.AnularFacturaOperationCompleted, userState);
        }
        
        private void OnAnularFacturaOperationCompleted(object arg) {
            if ((this.AnularFacturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AnularFacturaCompleted(this, new AnularFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seven/AnularH", RequestNamespace="http://seven/", ResponseNamespace="http://seven/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TSalida AnularH(int emp_codi, int fac_cont, string fac_esth) {
            object[] results = this.Invoke("AnularH", new object[] {
                        emp_codi,
                        fac_cont,
                        fac_esth});
            return ((TSalida)(results[0]));
        }
        
        /// <remarks/>
        public void AnularHAsync(int emp_codi, int fac_cont, string fac_esth) {
            this.AnularHAsync(emp_codi, fac_cont, fac_esth, null);
        }
        
        /// <remarks/>
        public void AnularHAsync(int emp_codi, int fac_cont, string fac_esth, object userState) {
            if ((this.AnularHOperationCompleted == null)) {
                this.AnularHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAnularHOperationCompleted);
            }
            this.InvokeAsync("AnularH", new object[] {
                        emp_codi,
                        fac_cont,
                        fac_esth}, this.AnularHOperationCompleted, userState);
        }
        
        private void OnAnularHOperationCompleted(object arg) {
            if ((this.AnularHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AnularHCompleted(this, new AnularHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seven/AnularFacturaConCruce", RequestNamespace="http://seven/", ResponseNamespace="http://seven/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AnularFacturaConCruce(int emp_codi, int fac_cont) {
            object[] results = this.Invoke("AnularFacturaConCruce", new object[] {
                        emp_codi,
                        fac_cont});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AnularFacturaConCruceAsync(int emp_codi, int fac_cont) {
            this.AnularFacturaConCruceAsync(emp_codi, fac_cont, null);
        }
        
        /// <remarks/>
        public void AnularFacturaConCruceAsync(int emp_codi, int fac_cont, object userState) {
            if ((this.AnularFacturaConCruceOperationCompleted == null)) {
                this.AnularFacturaConCruceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAnularFacturaConCruceOperationCompleted);
            }
            this.InvokeAsync("AnularFacturaConCruce", new object[] {
                        emp_codi,
                        fac_cont}, this.AnularFacturaConCruceOperationCompleted, userState);
        }
        
        private void OnAnularFacturaConCruceOperationCompleted(object arg) {
            if ((this.AnularFacturaConCruceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AnularFacturaConCruceCompleted(this, new AnularFacturaConCruceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seven/EliminarFactura", RequestNamespace="http://seven/", ResponseNamespace="http://seven/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EliminarFactura(int emp_codi, int fac_cont) {
            object[] results = this.Invoke("EliminarFactura", new object[] {
                        emp_codi,
                        fac_cont});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarFacturaAsync(int emp_codi, int fac_cont) {
            this.EliminarFacturaAsync(emp_codi, fac_cont, null);
        }
        
        /// <remarks/>
        public void EliminarFacturaAsync(int emp_codi, int fac_cont, object userState) {
            if ((this.EliminarFacturaOperationCompleted == null)) {
                this.EliminarFacturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarFacturaOperationCompleted);
            }
            this.InvokeAsync("EliminarFactura", new object[] {
                        emp_codi,
                        fac_cont}, this.EliminarFacturaOperationCompleted, userState);
        }
        
        private void OnEliminarFacturaOperationCompleted(object arg) {
            if ((this.EliminarFacturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarFacturaCompleted(this, new EliminarFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seven/InsertarFactura", RequestNamespace="http://seven/", ResponseNamespace="http://seven/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertarFactura(TSFaFactu pFactura) {
            object[] results = this.Invoke("InsertarFactura", new object[] {
                        pFactura});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertarFacturaAsync(TSFaFactu pFactura) {
            this.InsertarFacturaAsync(pFactura, null);
        }
        
        /// <remarks/>
        public void InsertarFacturaAsync(TSFaFactu pFactura, object userState) {
            if ((this.InsertarFacturaOperationCompleted == null)) {
                this.InsertarFacturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarFacturaOperationCompleted);
            }
            this.InvokeAsync("InsertarFactura", new object[] {
                        pFactura}, this.InsertarFacturaOperationCompleted, userState);
        }
        
        private void OnInsertarFacturaOperationCompleted(object arg) {
            if ((this.InsertarFacturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarFacturaCompleted(this, new InsertarFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://seven/GenerarReporteFaFactu", RequestNamespace="http://seven/", ResponseNamespace="http://seven/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TSalidaR GenerarReporteFaFactu(short emp_codi, short top_codi, int fac_nume, int fac_fech, string arb_cods, int fac_cont, short for_codi) {
            object[] results = this.Invoke("GenerarReporteFaFactu", new object[] {
                        emp_codi,
                        top_codi,
                        fac_nume,
                        fac_fech,
                        arb_cods,
                        fac_cont,
                        for_codi});
            return ((TSalidaR)(results[0]));
        }
        
        /// <remarks/>
        public void GenerarReporteFaFactuAsync(short emp_codi, short top_codi, int fac_nume, int fac_fech, string arb_cods, int fac_cont, short for_codi) {
            this.GenerarReporteFaFactuAsync(emp_codi, top_codi, fac_nume, fac_fech, arb_cods, fac_cont, for_codi, null);
        }
        
        /// <remarks/>
        public void GenerarReporteFaFactuAsync(short emp_codi, short top_codi, int fac_nume, int fac_fech, string arb_cods, int fac_cont, short for_codi, object userState) {
            if ((this.GenerarReporteFaFactuOperationCompleted == null)) {
                this.GenerarReporteFaFactuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerarReporteFaFactuOperationCompleted);
            }
            this.InvokeAsync("GenerarReporteFaFactu", new object[] {
                        emp_codi,
                        top_codi,
                        fac_nume,
                        fac_fech,
                        arb_cods,
                        fac_cont,
                        for_codi}, this.GenerarReporteFaFactuOperationCompleted, userState);
        }
        
        private void OnGenerarReporteFaFactuOperationCompleted(object arg) {
            if ((this.GenerarReporteFaFactuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerarReporteFaFactuCompleted(this, new GenerarReporteFaFactuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://seven/")]
    public partial class TSalida {
        
        private string retornoField;
        
        private string txtErrorField;
        
        /// <remarks/>
        public string Retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
            }
        }
        
        /// <remarks/>
        public string TxtError {
            get {
                return this.txtErrorField;
            }
            set {
                this.txtErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://seven/")]
    public partial class TSalidaR {
        
        private string retornoField;
        
        private string txtErrorField;
        
        private string ruta_pdfField;
        
        /// <remarks/>
        public string Retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
            }
        }
        
        /// <remarks/>
        public string TxtError {
            get {
                return this.txtErrorField;
            }
            set {
                this.txtErrorField = value;
            }
        }
        
        /// <remarks/>
        public string Ruta_pdf {
            get {
                return this.ruta_pdfField;
            }
            set {
                this.ruta_pdfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://seven/")]
    public partial class TSFaDanti {
        
        private int top_cantField;
        
        private int fac_nantField;
        
        private string fac_fantField;
        
        private string suc_cantField;
        
        private double fac_vranField;
        
        /// <remarks/>
        public int Top_cant {
            get {
                return this.top_cantField;
            }
            set {
                this.top_cantField = value;
            }
        }
        
        /// <remarks/>
        public int Fac_nant {
            get {
                return this.fac_nantField;
            }
            set {
                this.fac_nantField = value;
            }
        }
        
        /// <remarks/>
        public string Fac_fant {
            get {
                return this.fac_fantField;
            }
            set {
                this.fac_fantField = value;
            }
        }
        
        /// <remarks/>
        public string Suc_cant {
            get {
                return this.suc_cantField;
            }
            set {
                this.suc_cantField = value;
            }
        }
        
        /// <remarks/>
        public double Fac_vran {
            get {
                return this.fac_vranField;
            }
            set {
                this.fac_vranField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://seven/")]
    public partial class TSFaCtrlo {
        
        private int top_baseField;
        
        private int bas_numeField;
        
        private string bas_fechField;
        
        private string bas_csucField;
        
        private int bas_contField;
        
        /// <remarks/>
        public int Top_base {
            get {
                return this.top_baseField;
            }
            set {
                this.top_baseField = value;
            }
        }
        
        /// <remarks/>
        public int Bas_nume {
            get {
                return this.bas_numeField;
            }
            set {
                this.bas_numeField = value;
            }
        }
        
        /// <remarks/>
        public string Bas_fech {
            get {
                return this.bas_fechField;
            }
            set {
                this.bas_fechField = value;
            }
        }
        
        /// <remarks/>
        public string Bas_csuc {
            get {
                return this.bas_csucField;
            }
            set {
                this.bas_csucField = value;
            }
        }
        
        /// <remarks/>
        public int Bas_cont {
            get {
                return this.bas_contField;
            }
            set {
                this.bas_contField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://seven/")]
    public partial class TSFaDcoad {
        
        private string coa_codiField;
        
        private double coa_valoField;
        
        /// <remarks/>
        public string Coa_codi {
            get {
                return this.coa_codiField;
            }
            set {
                this.coa_codiField = value;
            }
        }
        
        /// <remarks/>
        public double Coa_valo {
            get {
                return this.coa_valoField;
            }
            set {
                this.coa_valoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://seven/")]
    public partial class TSFaCruau {
        
        private int top_codcField;
        
        private int fac_numcField;
        
        private System.DateTime fac_feccField;
        
        private string arb_succField;
        
        private double cru_valoField;
        
        private int cxc_contField;
        
        /// <remarks/>
        public int Top_codc {
            get {
                return this.top_codcField;
            }
            set {
                this.top_codcField = value;
            }
        }
        
        /// <remarks/>
        public int Fac_numc {
            get {
                return this.fac_numcField;
            }
            set {
                this.fac_numcField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Fac_fecc {
            get {
                return this.fac_feccField;
            }
            set {
                this.fac_feccField = value;
            }
        }
        
        /// <remarks/>
        public string Arb_succ {
            get {
                return this.arb_succField;
            }
            set {
                this.arb_succField = value;
            }
        }
        
        /// <remarks/>
        public double Cru_valo {
            get {
                return this.cru_valoField;
            }
            set {
                this.cru_valoField = value;
            }
        }
        
        /// <remarks/>
        public int Cxc_cont {
            get {
                return this.cxc_contField;
            }
            set {
                this.cxc_contField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://seven/")]
    public partial class TSFaDmfac {
        
        private string arb_codcField;
        
        private string arb_codaField;
        
        private string arb_codpField;
        
        private string arb_cossField;
        
        private string dmf_tipoField;
        
        private double dmf_valoField;
        
        private double dmf_porcField;
        
        /// <remarks/>
        public string Arb_codc {
            get {
                return this.arb_codcField;
            }
            set {
                this.arb_codcField = value;
            }
        }
        
        /// <remarks/>
        public string Arb_coda {
            get {
                return this.arb_codaField;
            }
            set {
                this.arb_codaField = value;
            }
        }
        
        /// <remarks/>
        public string Arb_codp {
            get {
                return this.arb_codpField;
            }
            set {
                this.arb_codpField = value;
            }
        }
        
        /// <remarks/>
        public string Arb_coss {
            get {
                return this.arb_cossField;
            }
            set {
                this.arb_cossField = value;
            }
        }
        
        /// <remarks/>
        public string Dmf_tipo {
            get {
                return this.dmf_tipoField;
            }
            set {
                this.dmf_tipoField = value;
            }
        }
        
        /// <remarks/>
        public double Dmf_valo {
            get {
                return this.dmf_valoField;
            }
            set {
                this.dmf_valoField = value;
            }
        }
        
        /// <remarks/>
        public double Dmf_porc {
            get {
                return this.dmf_porcField;
            }
            set {
                this.dmf_porcField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://seven/")]
    public partial class TSFaDdisp {
        
        private int tar_codiField;
        
        private string arb_codiField;
        
        private string ddi_tipoField;
        
        private double ddi_valoField;
        
        private double ddi_porcField;
        
        /// <remarks/>
        public int Tar_codi {
            get {
                return this.tar_codiField;
            }
            set {
                this.tar_codiField = value;
            }
        }
        
        /// <remarks/>
        public string Arb_codi {
            get {
                return this.arb_codiField;
            }
            set {
                this.arb_codiField = value;
            }
        }
        
        /// <remarks/>
        public string Ddi_tipo {
            get {
                return this.ddi_tipoField;
            }
            set {
                this.ddi_tipoField = value;
            }
        }
        
        /// <remarks/>
        public double Ddi_valo {
            get {
                return this.ddi_valoField;
            }
            set {
                this.ddi_valoField = value;
            }
        }
        
        /// <remarks/>
        public double Ddi_porc {
            get {
                return this.ddi_porcField;
            }
            set {
                this.ddi_porcField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://seven/")]
    public partial class TSFaDfact {
        
        private TSFaDdisp[] vDistribAField;
        
        private TSFaDmfac[] vDistribMField;
        
        private int bod_codiField;
        
        private string pro_codiField;
        
        private int uni_codiField;
        
        private double dfa_cantField;
        
        private double dfa_valoField;
        
        private string dfa_tideField;
        
        private double dfa_pvdeField;
        
        private string dfa_descField;
        
        private string dfa_destField;
        
        private int ctr_contField;
        
        private string cli_codaField;
        
        private short dcl_coddField;
        
        /// <remarks/>
        public TSFaDdisp[] vDistribA {
            get {
                return this.vDistribAField;
            }
            set {
                this.vDistribAField = value;
            }
        }
        
        /// <remarks/>
        public TSFaDmfac[] vDistribM {
            get {
                return this.vDistribMField;
            }
            set {
                this.vDistribMField = value;
            }
        }
        
        /// <remarks/>
        public int Bod_codi {
            get {
                return this.bod_codiField;
            }
            set {
                this.bod_codiField = value;
            }
        }
        
        /// <remarks/>
        public string Pro_codi {
            get {
                return this.pro_codiField;
            }
            set {
                this.pro_codiField = value;
            }
        }
        
        /// <remarks/>
        public int Uni_codi {
            get {
                return this.uni_codiField;
            }
            set {
                this.uni_codiField = value;
            }
        }
        
        /// <remarks/>
        public double Dfa_cant {
            get {
                return this.dfa_cantField;
            }
            set {
                this.dfa_cantField = value;
            }
        }
        
        /// <remarks/>
        public double Dfa_valo {
            get {
                return this.dfa_valoField;
            }
            set {
                this.dfa_valoField = value;
            }
        }
        
        /// <remarks/>
        public string Dfa_tide {
            get {
                return this.dfa_tideField;
            }
            set {
                this.dfa_tideField = value;
            }
        }
        
        /// <remarks/>
        public double Dfa_pvde {
            get {
                return this.dfa_pvdeField;
            }
            set {
                this.dfa_pvdeField = value;
            }
        }
        
        /// <remarks/>
        public string Dfa_desc {
            get {
                return this.dfa_descField;
            }
            set {
                this.dfa_descField = value;
            }
        }
        
        /// <remarks/>
        public string Dfa_dest {
            get {
                return this.dfa_destField;
            }
            set {
                this.dfa_destField = value;
            }
        }
        
        /// <remarks/>
        public int Ctr_cont {
            get {
                return this.ctr_contField;
            }
            set {
                this.ctr_contField = value;
            }
        }
        
        /// <remarks/>
        public string Cli_coda {
            get {
                return this.cli_codaField;
            }
            set {
                this.cli_codaField = value;
            }
        }
        
        /// <remarks/>
        public short Dcl_codd {
            get {
                return this.dcl_coddField;
            }
            set {
                this.dcl_coddField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://seven/")]
    public partial class TSFaFactu {
        
        private TSFaDfact[] vDetalleField;
        
        private TSFaCruau[] vCruceField;
        
        private TSFaDcoad[] vCAdicField;
        
        private TSFaCtrlo[] vDocBaseField;
        
        private TSFaDanti[] vAnticipoField;
        
        private int emp_codiField;
        
        private int top_codiField;
        
        private int fac_numeField;
        
        private System.DateTime fac_fechField;
        
        private string fac_descField;
        
        private string arb_csucField;
        
        private string cli_codaField;
        
        private int dcl_coddField;
        
        private int mon_codiField;
        
        private string fac_tdisField;
        
        private string fac_tipoField;
        
        private System.DateTime fac_fetaField;
        
        private System.DateTime fac_feciField;
        
        private System.DateTime fac_fecfField;
        
        private string fac_crefField;
        
        private System.DateTime fac_fepoField;
        
        private System.DateTime fac_fepeField;
        
        private System.DateTime fac_fextField;
        
        private int mco_contField;
        
        private string fac_tidoField;
        
        private double fac_pepeField;
        
        private double fac_pextField;
        
        private string fac_periField;
        
        private string fac_esthField;
        
        private string fac_estaField;
        
        private string usuarioField;
        
        private string passwordField;
        
        /// <remarks/>
        public TSFaDfact[] vDetalle {
            get {
                return this.vDetalleField;
            }
            set {
                this.vDetalleField = value;
            }
        }
        
        /// <remarks/>
        public TSFaCruau[] vCruce {
            get {
                return this.vCruceField;
            }
            set {
                this.vCruceField = value;
            }
        }
        
        /// <remarks/>
        public TSFaDcoad[] vCAdic {
            get {
                return this.vCAdicField;
            }
            set {
                this.vCAdicField = value;
            }
        }
        
        /// <remarks/>
        public TSFaCtrlo[] vDocBase {
            get {
                return this.vDocBaseField;
            }
            set {
                this.vDocBaseField = value;
            }
        }
        
        /// <remarks/>
        public TSFaDanti[] vAnticipo {
            get {
                return this.vAnticipoField;
            }
            set {
                this.vAnticipoField = value;
            }
        }
        
        /// <remarks/>
        public int Emp_codi {
            get {
                return this.emp_codiField;
            }
            set {
                this.emp_codiField = value;
            }
        }
        
        /// <remarks/>
        public int Top_codi {
            get {
                return this.top_codiField;
            }
            set {
                this.top_codiField = value;
            }
        }
        
        /// <remarks/>
        public int Fac_nume {
            get {
                return this.fac_numeField;
            }
            set {
                this.fac_numeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Fac_fech {
            get {
                return this.fac_fechField;
            }
            set {
                this.fac_fechField = value;
            }
        }
        
        /// <remarks/>
        public string Fac_desc {
            get {
                return this.fac_descField;
            }
            set {
                this.fac_descField = value;
            }
        }
        
        /// <remarks/>
        public string Arb_csuc {
            get {
                return this.arb_csucField;
            }
            set {
                this.arb_csucField = value;
            }
        }
        
        /// <remarks/>
        public string Cli_coda {
            get {
                return this.cli_codaField;
            }
            set {
                this.cli_codaField = value;
            }
        }
        
        /// <remarks/>
        public int Dcl_codd {
            get {
                return this.dcl_coddField;
            }
            set {
                this.dcl_coddField = value;
            }
        }
        
        /// <remarks/>
        public int Mon_codi {
            get {
                return this.mon_codiField;
            }
            set {
                this.mon_codiField = value;
            }
        }
        
        /// <remarks/>
        public string Fac_tdis {
            get {
                return this.fac_tdisField;
            }
            set {
                this.fac_tdisField = value;
            }
        }
        
        /// <remarks/>
        public string Fac_tipo {
            get {
                return this.fac_tipoField;
            }
            set {
                this.fac_tipoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Fac_feta {
            get {
                return this.fac_fetaField;
            }
            set {
                this.fac_fetaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Fac_feci {
            get {
                return this.fac_feciField;
            }
            set {
                this.fac_feciField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Fac_fecf {
            get {
                return this.fac_fecfField;
            }
            set {
                this.fac_fecfField = value;
            }
        }
        
        /// <remarks/>
        public string Fac_cref {
            get {
                return this.fac_crefField;
            }
            set {
                this.fac_crefField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Fac_fepo {
            get {
                return this.fac_fepoField;
            }
            set {
                this.fac_fepoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Fac_fepe {
            get {
                return this.fac_fepeField;
            }
            set {
                this.fac_fepeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Fac_fext {
            get {
                return this.fac_fextField;
            }
            set {
                this.fac_fextField = value;
            }
        }
        
        /// <remarks/>
        public int Mco_cont {
            get {
                return this.mco_contField;
            }
            set {
                this.mco_contField = value;
            }
        }
        
        /// <remarks/>
        public string Fac_tido {
            get {
                return this.fac_tidoField;
            }
            set {
                this.fac_tidoField = value;
            }
        }
        
        /// <remarks/>
        public double Fac_pepe {
            get {
                return this.fac_pepeField;
            }
            set {
                this.fac_pepeField = value;
            }
        }
        
        /// <remarks/>
        public double Fac_pext {
            get {
                return this.fac_pextField;
            }
            set {
                this.fac_pextField = value;
            }
        }
        
        /// <remarks/>
        public string Fac_peri {
            get {
                return this.fac_periField;
            }
            set {
                this.fac_periField = value;
            }
        }
        
        /// <remarks/>
        public string Fac_esth {
            get {
                return this.fac_esthField;
            }
            set {
                this.fac_esthField = value;
            }
        }
        
        /// <remarks/>
        public string Fac_esta {
            get {
                return this.fac_estaField;
            }
            set {
                this.fac_estaField = value;
            }
        }
        
        /// <remarks/>
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void InsertarFaFactuCompletedEventHandler(object sender, InsertarFaFactuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertarFaFactuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertarFaFactuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void InsertarFaDfactCompletedEventHandler(object sender, InsertarFaDfactCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertarFaDfactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertarFaDfactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AplicarFacturaCompletedEventHandler(object sender, AplicarFacturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AplicarFacturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AplicarFacturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AnularFacturaCompletedEventHandler(object sender, AnularFacturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AnularFacturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AnularFacturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AnularHCompletedEventHandler(object sender, AnularHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AnularHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AnularHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TSalida Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TSalida)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AnularFacturaConCruceCompletedEventHandler(object sender, AnularFacturaConCruceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AnularFacturaConCruceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AnularFacturaConCruceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void EliminarFacturaCompletedEventHandler(object sender, EliminarFacturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarFacturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarFacturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void InsertarFacturaCompletedEventHandler(object sender, InsertarFacturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertarFacturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertarFacturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GenerarReporteFaFactuCompletedEventHandler(object sender, GenerarReporteFaFactuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerarReporteFaFactuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerarReporteFaFactuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TSalidaR Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TSalidaR)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591